name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
        with:
          USERNAME: ${{ github.lanbertry }}
